IMPORT LIBRARY

In [2]:
import sys, os
current_dir = os.getcwd()
project_root = current_dir[:current_dir.find("src") - 1]
sys.path.insert(0, project_root)

import pandas as pd
import numpy as np
from data_selector import Data_selector
from feature_adder import Feature_adder
from feature_selector import Feature_selector
from logs.logger import CustomLogger
from models import Random_Forest, Linear
from src.root import get_root

# raw tables have null row? no!

In [4]:
import os

folder_path = project_root + "/data/interim"  # Replace with your folder path
file_names = [f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]

print("Files in folder:")
for file in file_names:
    csv_read_path = os.path.join(project_root, "data", "interim", file)
    df = pd.read_csv(csv_read_path, encoding='utf-8')
    null_counts = df.isnull().sum()
    print(file,null_counts.sum())

Files in folder:
bar.csv 0
commitment.csv 0
energy.csv 0
factors.csv 0
load.csv 0
plant_data.csv 0
selleroffer.csv 0
status.csv 0
weather.csv 0


In [36]:
import os

folder_path = project_root + "/data/processed"  # Replace with your folder path
file_names = [f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]

print("Files in folder:")
for file in file_names:
    csv_read_path = os.path.join(project_root, "data", "processed", file)
    df = pd.read_csv(csv_read_path, encoding='utf-8')
    null_counts = df.isnull().sum()
    print(file,len(df))
    print(null_counts)
    
print("end")

Files in folder:
Data_for_plot.csv 830774
id                               0
name                             0
code                             0
date                             0
hour                             0
temperature                      0
humidity                         0
dew                              0
apparent_temperature             0
precipitation                    0
rain                             0
snow                             0
surface_pressure                 0
evapotransporation               0
wind_speed                       0
wind_direction                   0
value                            0
forecast                         0
generation                       0
declare                          0
status                           0
require                          0
season                           0
datetime                         0
is_good_peak                     0
temperature_with_5_delay         0
prediction                  652165
dtype: int64


In [76]:
import os

folder_path = project_root + "/data/interim"  # Replace with your folder path
file_names = [f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]

print("Files in folder:")
for file in file_names:
    csv_read_path = os.path.join(project_root, "data", "interim", file)
    df = pd.read_csv(csv_read_path, encoding='utf-8')
    null_counts = df.isnull().sum()
    print(file,len(df))
    print(null_counts)
    
print("end")

Files in folder:
bar.csv 35064
date     0
hour     0
value    0
dtype: int64
commitment.csv 1590288
id         0
name       0
code       0
date       0
hour       0
require    0
dtype: int64
energy.csv 3309408
id            0
code          0
name          0
date          0
hour          0
generation    0
dtype: int64
factors.csv 105192
id      0
name    0
code    0
date    0
a       0
b       0
dtype: int64
load.csv 36650
date        0
hour        0
forecast    0
dtype: int64
plant_data.csv 161
id      0
name    0
type    0
utm     0
dtype: int64
selleroffer.csv 3675374
id         0
name       0
code       0
date       0
hour       0
declare    0
dtype: int64
status.csv 3712284
id        0
code      0
date      0
hour      0
status    0
dtype: int64
weather.csv 455195
unitid                  0
date                    0
time                    0
temperature_2m          0
relative_humidity_2m    0
dew_point_2m            0
apparent_temperature    0
precipitation           0
rain         

# Print size of csvs in 2 folder

In [10]:
import os
folder_path = project_root + "/data/interim"  # Replace with your folder path
file_names = np.array([f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))])
arr = np.array([len(pd.read_csv(os.path.join(project_root, "data", "interim", file), encoding='utf-8')) for file in file_names])
index = arr.argsort()
arr1 = arr[index]
file_names1 = file_names[index]

In [11]:
import os

folder_path = project_root + "/data/raw"  # Replace with your folder path
file_names = np.array([f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))])
arr = np.array([len(pd.read_csv(os.path.join(project_root, "data", "raw", file), encoding='utf-8')) for file in file_names])
index = arr.argsort()
arr2 = arr[index]
file_names2 = file_names[index]

C:\Users\alireza\AppData\Local\Temp\ipykernel_31880\441354566.py:5: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  arr = np.array([len(pd.read_csv(os.path.join(project_root, "data", "raw", file), encoding='utf-8')) for file in file_names])


In [12]:
b1 = list(zip(file_names1,arr1))
b2 = list(zip(file_names2,arr2))
[print(k) for k in list(zip(b1,b2))]

(('plant_data.csv', 161), ('commitment_check.csv', 108))
(('bar.csv', 35064), ('PlantData.csv', 161))
(('load.csv', 36650), ('LowMiddlePeakLoadHours_View.csv', 35064))
(('factors.csv', 105192), ('LoadPredictionNetwork.csv', 36675))
(('weather.csv', 455195), ('TemperatureFactors_View.csv', 105192))
(('commitment.csv', 1590288), ('PowerplantUnitEnergy_View.csv', 138480))
(('energy.csv', 3309408), ('PlantsTemperature_View.csv', 762866))
(('selleroffer.csv', 3675374), ('UnitsStatusChangeLastRev_Hourly_View.csv', 3712366))
(('status.csv', 3712284), ('SellerOffer_View.csv', 5236124))


[None, None, None, None, None, None, None, None, None]

# count duplcate row

In [33]:
def get_info(folder):
    folder_path = project_root + f"/data/{folder}"  # Replace with your folder path
    file_names = [f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]

    file_info = {}
    print(f"Files in folder: {folder}")
    for file in file_names:
        csv_read_path = os.path.join(project_root, "data", folder, file)
        df = pd.read_csv(csv_read_path, encoding='utf-8')
        duplicate_rows_count = len(df.dropna())
        file_info[file] = (len(df),duplicate_rows_count,len(df)-duplicate_rows_count)
        
    return file_info


In [34]:
inf1 = get_info("raw")
inf2 = get_info("interim")

Files in folder: raw


C:\Users\alireza\AppData\Local\Temp\ipykernel_31880\2128495288.py:9: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_read_path, encoding='utf-8')


Files in folder: interim


!! - weather  X
PlantsTemperature_View.csv -- !! X
commitment_check.csv -- !! X

LoadPredictionNetwork.csv -- load X(25)
LowMiddlePeakLoadHours_View.csv -- bar X
PlantData.csv -- plant_data X
PowerplantUnitEnergy_View.csv -- energy X
SellerOffer_View.csv -- selleroffer X
TemperatureFactors_View.csv -- factors X
UnitCommitment.csv -- commitment X
UnitsStatusChangeLastRev_Hourly_View.csv -- status X


In [35]:
inf1,inf2

({'commitment_check.csv': (108, 108, 0),
  'LoadPredictionNetwork.csv': (36675, 36675, 0),
  'LowMiddlePeakLoadHours_View.csv': (35064, 35064, 0),
  'PlantData.csv': (161, 161, 0),
  'PlantsTemperature_View.csv': (762866, 744623, 18243),
  'PowerplantUnitEnergy_View.csv': (138480, 138480, 0),
  'SellerOffer_View.csv': (5236124, 5236124, 0),
  'TemperatureFactors_View.csv': (105192, 105192, 0),
  'UnitCommitment.csv': (5242416, 1855088, 3387328),
  'UnitsStatusChangeLastRev_Hourly_View.csv': (3712366, 3712284, 82)},
 {'bar.csv': (35064, 35064, 0),
  'commitment.csv': (1590288, 1590288, 0),
  'energy.csv': (3309408, 3309408, 0),
  'factors.csv': (105192, 105192, 0),
  'load.csv': (36650, 36650, 0),
  'plant_data.csv': (161, 161, 0),
  'selleroffer.csv': (3675374, 3675374, 0),
  'status.csv': (3712284, 3712284, 0),
  'weather.csv': (455195, 455195, 0)})

In [76]:
null_counts = df.isnull().sum()
print("Null count per column:")
print(null_counts)

Null count per column:
id            0
code          0
name          0
date          0
hour          0
generation    0
dtype: int64


In [ ]:
power_plants = df[['name', 'code']].drop_duplicates()
b = {}
for _, row in power_plants.iterrows():
    df1 = Data_selector(df).filter_name_code(row["name"],row["code"])
    df1.loc[df1.index,'datetime'] = pd.to_datetime(df1['date']) + pd.to_timedelta(df1['hour'], unit='h')
    df1 = df1.sort_values(by='datetime')
    b[(row["name"],row["code"])] = (df1["datetime"].head(1).to_numpy()[0],df1["datetime"].tail(1).to_numpy()[0])

In [ ]:
power_plants = df[['name', 'code']].drop_duplicates()
for _, row in power_plants.iterrows():
    print((row["name"],row["code"]))
    print(b[(row["name"],row["code"])])

In [72]:
csv_read_path = os.path.join(project_root, "data", "raw", "LoadPredictionNetwork.csv")
df1 = pd.read_csv(csv_read_path, encoding='utf-8')
df1.drop(columns=["Revision"],inplace=True)
df1.rename(columns={'HourNo': 'hour', "ForcastedValue":"forecast"}, inplace=True)

In [73]:
csv_read_path = os.path.join(project_root, "data", "interim", "load.csv")
df2 = pd.read_csv(csv_read_path, encoding='utf-8')

In [75]:
print(len(df2),len(df1))
print(len(df2.drop_duplicates()),len(df1.drop_duplicates()))

36650 36675
36650 36650


In [62]:
import pandas as pd

# Sample DataFrames
df1 = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40]
})

df2 = pd.DataFrame({
    'ID': [1, 3, 4, 5],
    'Name': ['Alice', 'Charlie', 'David', 'Eva'],  # Bob deleted, Eva new
    'Age': [26, 35, 41, 22]  # Alice and David ages updated
})

# Mark changes using merge
df_merged = df1.merge(df2, on='ID', how='outer', suffixes=('_old', '_new'), indicator=True)

# Detect row state
def detect_change(row):
    if row['_merge'] == 'left_only':
        return 'Deleted'
    elif row['_merge'] == 'right_only':
        return 'New'
    else:  # present in both, check if changed
        if (row['Name_old'] != row['Name_new']) or (row['Age_old'] != row['Age_new']):
            return 'Updated'
        else:
            return 'Unchanged'

df_merged['Change'] = df_merged.apply(detect_change, axis=1)

# Show rows with changes only
diff_df = df_merged[df_merged['Change'] != 'Unchanged']

print(diff_df[['ID', 'Name_old', 'Name_new', 'Age_old', 'Age_new', 'Change']])


   ID Name_old Name_new  Age_old  Age_new   Change
0   1    Alice    Alice     25.0     26.0  Updated
1   2      Bob      NaN     30.0      NaN  Deleted
3   4    David    David     40.0     41.0  Updated
4   5      NaN      Eva      NaN     22.0      New


In [ ]:
def getcsv(p1,p2):
    csv_read_path = os.path.join(project_root, "data", p1,p2)
    df = pd.read_csv(csv_read_path, encoding='utf-8')
    return df

In [107]:
def get_domain_name_code(df):
    power_plants = df[['name', 'code']].drop_duplicates()
    ds = Data_selector(df)
    b = []
    for _, row in power_plants.iterrows():
        df_name_code = ds.filter_name_code(row["name"], row["code"])
        #print("%%%%%%%%")
        #print(row["name"], row["code"])
        #print(len(df_name_code))
        b.append(len(df_name_code))
        if len(df_name_code) == 16080:
            print(row["name"], row["code"])
            print("%%%%%%%%")
            break
    return np.unique(np.array(b),return_counts=True)

In [108]:
df = getcsv("interim","energy.csv")
a,b = get_domain_name_code(df)
null_counts = df.isnull().sum()

سيکل ترکيبي شهداي پيروز G13
%%%%%%%%


In [109]:
a,b

(array([16080, 34152, 34224, 34248, 34392]),
 array([ 1,  1,  6, 11, 26], dtype=int64))

In [110]:
null_counts

id            0
code          0
name          0
date          0
hour          0
generation    0
dtype: int64

In [117]:
df = getcsv("processed","integrated.csv")

In [118]:
df = df.dropna().drop_duplicates()
b = df[['name', 'code']].drop_duplicates()
len(b)

52

In [119]:
len(df)

831024

In [120]:
a,b = get_domain_name_code(df)

In [121]:
a,b

(array([ 4200,  9192, 11280, 12384, 12408, 34440, 34464]),
 array([ 1,  1,  1,  5, 35,  1,  8], dtype=int64))